# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

target 'turnip' do

pod 'Parse'
pod 'ParseFacebookUtilsV4'
pod 'ParseCrashReporting'
pod 'ParseUI'
pod 'Facebook-iOS-SDK', '~> 4.0.1'
pod 'Google-Maps-iOS-SDK', '~> 1.9'
pod 'MCSwipeTableViewCell', '~> 2.1.2'
pod 'Reachability'
pod 'AMBubbleTableViewController'
pod 'AFNetworking', '~> 2.0'

end

target 'turnipTests' do

end

