# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

target 'turnip' do

pod 'Parse'
pod 'ParseFacebookUtilsV4'
pod 'ParseCrashReporting'
pod 'ParseUI'
pod 'GoogleMaps'
pod 'MCSwipeTableViewCell', '~> 2.1.2'
pod 'Reachability'
pod 'AMBubbleTableViewController'
pod 'AFNetworking', '~> 2.0'
pod 'FBSDKCoreKit', '~> 4.2.0'
pod 'FBSDKShareKit', '~> 4.2.0'
pod 'FBSDKLoginKit', '~> 4.2.0'
pod 'TPKeyboardAvoiding', :git => 'https://github.com/darrenallen7/TPKeyboardAvoiding'
pod 'MDCSwipeToChoose'


end

target 'turnipTests' do

end

